export const MIDI_STATUS_SYSTEM_TIMING_CLOCK = 248;
export const MIDI_STATUS_SYSTEM_START_SEQUENCE = 250;
export const MIDI_STATUS_SYSTEM_CONTINUE_SEQUENCE = 251;
export const MIDI_STATUS_SYSTEM_STOP_SEQUENCE = 252;
export const MIDI_STATUS_SYSTEM_ACTIVE_SENSING = 254;
export const MIDI_STATUS_SYSTEM_SYSTEM_RESET = 255;

export const MIDI_STATUS_CHANNEL_NOTE_OFF = 128;
export const MIDI_STATUS_CHANNEL_NOTE_ON = 144;
export const MIDI_STATUS_CHANNEL_POLYPHONIC_KEY_PRESSURE = 160;
export const MIDI_STATUS_CHANNEL_CONTROL_CHANGE = 176;
export const MIDI_STATUS_CHANNEL_PROGRAM_CHANGE = 192;
export const MIDI_STATUS_CHANNEL_CHANNEL_PRESSURE = 208;
export const MIDI_STATUS_CHANNEL_PITCH_BEND = 224;
